version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false  
    restart: always
# new Superserver Port
    ports: 
#      - 51773
      - 1972
      - 42773:52773
      - 53773
    volumes:
# no license required for community image
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
